In [ ]:
## this code in originally Ruth's

In [3]:
#source activate newEnv
suppressMessages(library(hdf5r))
suppressMessages(library(Seurat))
suppressMessages(library(Signac))
suppressMessages(library(EnsDb.Hsapiens.v86))
suppressMessages(library(dplyr))
suppressMessages(library(ggplot2))
suppressMessages(library(Matrix))
suppressMessages(library(harmony))
suppressMessages(library(data.table))
suppressMessages(library(ggpubr))
suppressMessages(library(future))
library(Seurat)
library(ggplot2)
library(sctransform)
#library(scater)
library(reticulate)
library(future)
#library('gPCA')
library('Biobase')
#library(pheatmap)
#library("ggfortify")
#library('qvalue')
library(gplots)
#library('DESeq2')
#library(VennDiagram)
library('hdf5r')
library(EnsDb.Hsapiens.v86)
#library(EnsDb.Mmusculus.v79)
library(BiocParallel)
#library(tictoc)
library(Seurat)
library(Signac)
library(EnsDb.Hsapiens.v86)
library(ggplot2)
library(cowplot)
library(GenomeInfoDb)
library(stats)
library("Signac")
library(tibble)
library(broom)
library("tictoc")
library("parallel")
library(tidyr)
library("dplyr")

Attaching package: 'gplots'


The following object is masked from 'package:IRanges':

    space


The following object is masked from 'package:S4Vectors':

    space


The following object is masked from 'package:stats':

    lowess



Attaching package: 'cowplot'


The following object is masked from 'package:ggpubr':

    get_legend



Attaching package: 'tictoc'


The following object is masked from 'package:data.table':

    shift


The following object is masked from 'package:GenomicRanges':

    shift


The following object is masked from 'package:IRanges':

    shift



Attaching package: 'tidyr'


The following objects are masked from 'package:Matrix':

    expand, pack, unpack


The following object is masked from 'package:S4Vectors':

    expand

### take logistic regression results -- make a bed file of sig peaks

In [6]:
cells <- scan('/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/HOMER/rerun_directionity/celltypes.txt', what="", sep="\n")
cells

 [1] "Beta"               "Alpha"              "Acinar_4"
 [4] "Activated_Stellate" "Endothelial"        "Quiescent_Stellate"
 [7] "Tcells"             "Macrophage"         "Acinar_5"
[10] "Ductal"

In [8]:
dir.create('inputs')

In [14]:
### get pval sig CREs
disease_use <- c('earlyT1D','Aab','lateT1D')

for (CELL in cells){
        for (disease_num in 1:length(disease_use)){
        file_name <- paste0(sprintf('/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/marker_CREs/disease_differences/051524_LogReg/logReg_results_WestonCovar_min10_%s/%s.LogReg.txt', CELL,disease_use[disease_num]))
        if (file.exists(file_name)) {
            print(file_name)
            res <- read.table(file_name, sep = '\t', header = TRUE)
            pval_col <- paste0('pvalue_',disease_use[disease_num])

            res <- subset(res, subset = res[pval_col] < 0.05)
            res <- subset(res, select=-c(std.error,estimate))
            res <- select(res, -contains(c("fdr_")))
            res$celltype <- CELL
            res <- separate(res, peak, into = c("chr", "start", "end"), sep = "_")
            res <- res[,colnames(res) %in% c("chr", "start", "end")]

            write.table(res, sprintf('inputs/%s_%s_pval05.bed',CELL,disease_use[disease_num]), sep = '\t', quote = FALSE, col.names = FALSE, row.names = FALSE)
        }  
    }
} 

celltype = c('Beta')
disease_use <- c('earlyT1D','Aab','lateT1D')

for (CELL in celltype){
        for (disease_num in 1:length(disease_use)){
        file_name <- paste0(sprintf('/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/marker_CREs/disease_differences/051524_LogReg/logReg_results_WestonCovar_min10_betaPropCovar/%s.LogReg.txt',disease_use[disease_num]))
        if (file.exists(file_name)) {
            print(file_name)
            res <- read.table(file_name, sep = '\t', header = TRUE)
            pval_col <- paste0('pvalue_',disease_use[disease_num])

            res <- subset(res, subset = res[pval_col] < 0.05)
            res <- subset(res, select=-c(std.error,estimate))
            res <- select(res, -contains(c("fdr_")))
            res$celltype <- CELL
            res <- separate(res, peak, into = c("chr", "start", "end"), sep = "_")
            res <- res[,colnames(res) %in% c("chr", "start", "end")]

            write.table(res, sprintf('inputs/%s_%s_pval05.bed',CELL,disease_use[disease_num]), sep = '\t', quote = FALSE, col.names = FALSE, row.names = FALSE)
        }  
    }
}

[1] "/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/marker_CREs/disease_differences/051524_LogReg/logReg_results_WestonCovar_min10_Alpha/earlyT1D.LogReg.txt"
[1] "/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/marker_CREs/disease_differences/051524_LogReg/logReg_results_WestonCovar_min10_Alpha/Aab.LogReg.txt"
[1] "/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/marker_CREs/disease_differences/051524_LogReg/logReg_results_WestonCovar_min10_Alpha/lateT1D.LogReg.txt"
[1] "/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/marker_CREs/disease_differences/051524_LogReg/logReg_results_WestonCovar_min10_Acinar_4/earlyT1D.LogReg.txt"
[1] "/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/marker_CREs/disease_differences/051524_LogReg/logReg_results_WestonCovar_min10_Acinar_4/Aab.LogReg.txt"
[1] "/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/marker_CREs/disease_differences/051524_LogReg/logReg_results_WestonCovar_min10_Acinar_4/lateT1D.LogReg.txt"
[1] "/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/marker_CREs/disease_differences/051524_LogReg/logReg_results_WestonCovar_min10_Activated_Stellate/earlyT1D.LogReg.txt"
[1] "/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/marker_CREs/disease_differences/051524_LogReg/logReg_results_WestonCovar_min10_Activated_Stellate/Aab.LogReg.txt"
[1] "/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/marker_CREs/disease_differences/051524_LogReg/logReg_results_WestonCovar_min10_Activated_Stellate/lateT1D.LogReg.txt"
[1] "/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/marker_CREs/disease_differences/051524_LogReg/logReg_results_WestonCovar_min10_Endothelial/earlyT1D.LogReg.txt"
[1] "/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/marker_CREs/disease_differences/051524_LogReg/logReg_results_WestonCovar_min10_Endothelial/Aab.LogReg.txt"
[1] "/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/marker_CREs/disease_differences/051524_LogReg/logReg_results_WestonCovar_min10_Endothelial/lateT1D.LogReg.txt"
[1] "/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/marker_CREs/disease_differences/051524_LogReg/logReg_results_WestonCovar_min10_Quiescent_Stellate/earlyT1D.LogReg.txt"
[1] "/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/marker_CREs/disease_differences/051524_LogReg/logReg_results_WestonCovar_min10_Quiescent_Stellate/Aab.LogReg.txt"
[1] "/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/marker_CREs/disease_differences/051524_LogReg/logReg_results_WestonCovar_min10_Quiescent_Stellate/lateT1D.LogReg.txt"
[1] "/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/marker_CREs/disease_differences/051524_LogReg/logReg_results_WestonCovar_min10_Tcells/earlyT1D.LogReg.txt"
[1] "/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/marker_CREs/disease_differences/051524_LogReg/logReg_results_WestonCovar_min10_Tcells/Aab.LogReg.txt"
[1] "/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/marker_CREs/disease_differences/051524_LogReg/logReg_results_WestonCovar_min10_Tcells/lateT1D.LogReg.txt"
[1] "/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/marker_CREs/disease_differences/051524_LogReg/logReg_results_WestonCovar_min10_Macrophage/earlyT1D.LogReg.txt"
[1] "/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/marker_CREs/disease_differences/051524_LogReg/logReg_results_WestonCovar_min10_Macrophage/Aab.LogReg.txt"
[1] "/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/marker_CREs/disease_differences/051524_LogReg/logReg_results_WestonCovar_min10_Macrophage/lateT1D.LogReg.txt"
[1] "/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/marker_CREs/disease_differences/051524_LogReg/logReg_results_WestonCovar_min10_Acinar_5/earlyT1D.LogReg.txt"
[1] "/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/marker_CREs/disease_differences/051524_LogReg/logReg_results_WestonCovar_min10_Acinar_5/Aab.LogReg.txt"
[1] "/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/marker_CREs/disease_differences/051524_LogReg/logReg_results_WestonCovar_min10_Acinar_5/lateT1D.LogReg.txt"
[1] "/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/marker_CREs/disease_differences/051524_LogReg/logReg_results_WestonCovar_min10_Ductal/earlyT1D.LogReg.txt"
[1] "/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/marker_CREs/disease_differences/051524_LogReg/logReg_results_WestonCovar_min10_Ductal/Aab.LogReg.txt"
[1] "/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/marker_CREs/disease_differences/051524_LogReg/logReg_results_WestonCovar_min10_Ductal/lateT1D.LogReg.txt"
[1] "/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/marker_CREs/disease_differences/051524_LogReg/logReg_results_WestonCovar_min10_betaPropCovar/earlyT1D.LogReg.txt"
[1] "/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/marker_CREs/disease_differences/051524_LogReg/logReg_results_WestonCovar_min10_betaPropCovar/Aab.LogReg.txt"

### sort bed files

```bash
#!/bin/bash

# Loop over all .bed files in the current directory
for file in *.bed; do
  # Construct the output file name by appending .sorted.bed
  sorted_file="${file%.bed}.sorted.bed"
  # Sort the file by the first and second columns and save the result
  sort -k1,1 -k2,2n "$file" > "$sorted_file"
  echo "Sorted $file and saved to $sorted_file"
done

```

### get background peaks aka all peaks called in cell type

In [17]:
dir.create('backgrounds')
### get background peaks

for (CELL in cells){
    file_name <- paste0(sprintf('/nfs/lab/projects/nPOD/downstream_files/ATAC/final_peakcall/peakCallOutput_qvalue05_UNparallelized_20230118/%s_peaks.bed',CELL))
    if (file.exists(file_name)) {
            print(file_name)
            file.copy(file_name, 'backgrounds/')
        }  
    }

Warning message in dir.create("backgrounds"):
"'backgrounds' already exists"

[1] "/nfs/lab/projects/nPOD/downstream_files/ATAC/final_peakcall/peakCallOutput_qvalue05_UNparallelized_20230118/Beta_peaks.bed"
[1] "/nfs/lab/projects/nPOD/downstream_files/ATAC/final_peakcall/peakCallOutput_qvalue05_UNparallelized_20230118/Alpha_peaks.bed"
[1] "/nfs/lab/projects/nPOD/downstream_files/ATAC/final_peakcall/peakCallOutput_qvalue05_UNparallelized_20230118/Acinar_4_peaks.bed"
[1] "/nfs/lab/projects/nPOD/downstream_files/ATAC/final_peakcall/peakCallOutput_qvalue05_UNparallelized_20230118/Activated_Stellate_peaks.bed"
[1] "/nfs/lab/projects/nPOD/downstream_files/ATAC/final_peakcall/peakCallOutput_qvalue05_UNparallelized_20230118/Endothelial_peaks.bed"
[1] "/nfs/lab/projects/nPOD/downstream_files/ATAC/final_peakcall/peakCallOutput_qvalue05_UNparallelized_20230118/Quiescent_Stellate_peaks.bed"
[1] "/nfs/lab/projects/nPOD/downstream_files/ATAC/final_peakcall/peakCallOutput_qvalue05_UNparallelized_20230118/Tcells_peaks.bed"
[1] "/nfs/lab/projects/nPOD/downstream_files/ATAC/final_peakcall/peakCallOutput_qvalue05_UNparallelized_20230118/Macrophage_peaks.bed"
[1] "/nfs/lab/projects/nPOD/downstream_files/ATAC/final_peakcall/peakCallOutput_qvalue05_UNparallelized_20230118/Acinar_5_peaks.bed"
[1] "/nfs/lab/projects/nPOD/downstream_files/ATAC/final_peakcall/peakCallOutput_qvalue05_UNparallelized_20230118/Ductal_peaks.bed"

## Run Finrich

In [18]:
getwd()

[1] "/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/Finrich/finemap"

```bash
# test single finrich 
finrich /nfs/lab/hmummey/multiomic_islet/intermediates/221102_variant_overlaps/GWAS_credible_sets/T1D_JChiou_99credset.bed /nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/Finrich/finemap/inputs/Acinar_4_Aab_pval05.sorted.bed /nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/Finrich/finemap/backgrounds/Acinar_4_peaks.bed --permutations 1000 --processes 2

```

In [20]:
trait_beds <- list.files('inputs/', full.names = TRUE) #full.names makes sure you have the full file path
cell_type_beds <- list.files('', full.names = TRUE)


background_beds <- list.files('backgrounds/', full.names = TRUE)

results2 <- NULL #Create an empty dataframe to store results from loop

for (CELL in cells){
        for (disease_num in 1:length(disease_use)){
            input_name <- paste0(sprintf('inputs/%s_%s_pval05.sorted.bed', CELL,disease_use[disease_num]))
            if (file.exists(input_name)) {
                background_name <- paste0(sprintf('backgrounds/%s_peaks.bed', CELL))
                res <- system(paste0('finrich /nfs/lab/hmummey/multiomic_islet/intermediates/221102_variant_overlaps/GWAS_credible_sets/T1D_JChiou_99credset.bed ', input_name, ' ', background_name,' --permutations 1000 --processes 2'), intern = TRUE)
                res <- strsplit(res, ":|,|}")
                res <- as.data.frame(res)
                if (length(res > 0)){
                    results <- data.frame(matrix(ncol=0, nrow=1))
                    results$disease_condition <- disease_use[disease_num]
                    results$cell_type <- CELL
                    results$pval <- res[2,]
                    results$fold_enrich <- res[4,]
                    results$logOR <- res[6,]
                    results$conf_lower <- res[8,]
                    results$conf_upper  <- res[10,]
                    results2 <- rbind(results, results2)
                }
        }
    }
}


results2$pval <- as.numeric(results2$pval)
results2$log10p <- -log10(results2$pval)
head(results2)

  disease_condition cell_type pval  fold_enrich         logOR
1 lateT1D           Ductal    0.265  1.2747026788854656  0.2527932672761093
2 Aab               Ductal    0.284  1.0747629461257127  0.07391675564461608
3 earlyT1D          Ductal    0.623  0.3715477025967056  -1.0132410037971018
4 lateT1D           Acinar_5  0.088  3.595239768746183   1.3836897440112912
5 Aab               Acinar_5  0.121  2.6241596084595895  1.0240381870776265
6 earlyT1D          Acinar_5  0.022  6.880413547603774   2.0730696689148997
  conf_lower           conf_upper          log10p
1  -1.2108462794341315  4.33304042232603   0.5767541
2  -1.5450924633012313  5.8735202234305275 0.5466817
3  -2.529715229080508   3.436564246815251  0.2055120
4  -0.3636686834424716  7.962011498445181  1.0555173
5  -0.7290695619151834  7.80621420439549   0.9172146
6  0.05735570050588839  14.460783715195662 1.6575773

In [22]:
results2$fdr <- p.adjust(results2$pval, method = 'BH')
results2

   disease_condition cell_type          pval  fold_enrich
1  lateT1D           Ductal             0.265  1.2747026788854656
2  Aab               Ductal             0.284  1.0747629461257127
3  earlyT1D          Ductal             0.623  0.3715477025967056
4  lateT1D           Acinar_5           0.088  3.595239768746183
5  Aab               Acinar_5           0.121  2.6241596084595895
6  earlyT1D          Acinar_5           0.022  6.880413547603774
7  lateT1D           Macrophage         0.500  0.5718673333217735
8  Aab               Macrophage         0.230  1.539862841925114
9  earlyT1D          Macrophage         0.101  1.985182081706244
10 lateT1D           Tcells             0.320  0.9667034439145847
11 Aab               Tcells             0.231  1.4872774512332223
12 earlyT1D          Tcells             0.386  0.8062494148074973
13 lateT1D           Quiescent_Stellate 0.000  11.021253924841028
14 Aab               Quiescent_Stellate 0.258  1.0886630550304572
15 earlyT1D          Quiescent_Stellate 0.474  0.4303113058306738
16 lateT1D           Endothelial        0.230  1.2902630110014108
17 Aab               Endothelial        0.362  0.812802726682214
18 earlyT1D          Endothelial        0.004  6.4346735914712125
19 lateT1D           Activated_Stellate 0.294  1.2757342801324845
20 Aab               Activated_Stellate 0.266  1.378526884962623
21 earlyT1D          Activated_Stellate 0.432  0.9929959026320789
22 lateT1D           Acinar_4           0.578  0.1506261296959727
23 Aab               Acinar_4           0.655  0.05602039142247779
24 earlyT1D          Acinar_4           0.777  0.010124647061131354
25 lateT1D           Alpha              0.167  1.7616402048981867
26 Aab               Alpha              0.066  3.468390692682841
27 earlyT1D          Alpha              0.877  0.0767783968578786
28 Aab               Beta               0.747  0.102048921411284
29 earlyT1D          Beta               0.245  1.1244982065923645
   logOR                  conf_lower            conf_upper          log10p
1   0.2527932672761093     -1.2108462794341315   4.33304042232603   0.57675413
2   0.07391675564461608    -1.5450924633012313   5.8735202234305275 0.54668166
3   -1.0132410037971018    -2.529715229080508    3.436564246815251  0.20551195
4   1.3836897440112912     -0.3636686834424716   7.962011498445181  1.05551733
5   1.0240381870776265     -0.7290695619151834   7.80621420439549   0.91721463
6   2.0730696689148997     0.05735570050588839   14.460783715195662 1.65757732
7   -0.5702459350764282    -2.04471393193488     3.8169993027744233 0.30103000
8   0.4530076915387742     -0.8946695009626973   3.756240711690443  0.63827216
9   0.7473137986322849     -0.42519541077694223  3.0307231216826906 0.99567863
10  -0.034660658066200556  -1.6256181522941002   5.4856972549303125 0.49485002
11  0.4117580347044003     -1.0407054086659353   4.551045393284975  0.63638802
12  -0.22084383417238151   -1.7276166363403838   4.385773079944917  0.41341270
13  2.6305066071826344     0.7131884611194236    13.146076957522752        Inf
14  0.08740023528114627    -1.8153901358523932   9.58908915700939   0.58838029
15  -0.8578965545740975    -2.7413884742450025   8.468116289054791  0.32422166
16  0.263827006321383      -1.4823976767789468   7.216200993479667  0.63827216
17  -0.2123399878154053    -1.9869385696616741   7.330153829585326  0.44129143
18  2.084659065962552      0.413870621288177     7.907674950215826  2.39794001
19  0.2606479776204609     -1.0055628658223443   2.9059273862480186 0.53165267
20  0.33798564352036475    -1.0341466653728548   3.699525508906622  0.57511836
21  -0.007609444404792942  -1.1264618149799368   1.9642862319727965 0.36451625
22  -1.9199622237401404    -3.9413188279577085   9.294785047435997  0.23807216
23  -2.9006470039444605    -5.087798407796264    15.308342741705331 0.18375870
24  -4.608166502633805     -6.821616045203307    16.105599791434386 0.10957898
25  0.5903719004698269     -1.050293976523397    6.330329797206313  0.77728353
26  1.3225019559107656     -0.2793013552897827   6.70139094854601   1.18045606
27  -2.5998134366379295    -4.155457709119556    2.1877084693996203 0.05700041
28  -2.3062618550971434    -4.092885185483965    5.415009125577862  0.12667940
29  0.12133539952118322    -1.6283280335283261   7.046373401169639  0.61083392
   fdr
1  0.5015294
2  0.5015294
3  0.7226800
4  0.4881667
5  0.5012857
6  0.2126667
7  0.6304348
8  0.5015294
9  0.4881667
10 0.5155556
11 0.5015294
12 0.5597000
13 0.0000000
14 0.5015294
15 0.6248182
16 0.5015294
17 0.5525263
18 0.0580000
19 0.5015294
20 0.5015294
21 0.5965714
22 0.6984167
23 0.7305769
24 0.8047500
25 0.5015294
26 0.4785000
27 0.8770000
28 0.8023333
29 0.5015294

In [23]:
write.table(results2,'results.txt', sep = '\t', quote = FALSE, col.names = TRUE, row.names = FALSE)

In [24]:
getwd()

[1] "/nfs/lab/rlmelton/npod/notebooks/sherlock/Downstream_analysis_nPOD_april2022/Publication/Final_Downstream/Finrich/finemap"